### ISSUE TITLE
Implement parity-based post-processing of measurements

### ISSUE THREAD

**Issue by estebanag** [TNO-Quantum/ml.classifiers.vc#1]
## QHack 2023 Hackathon 

This issue is related to one of our contributions to the [QHack 2023 Hackathon](https://qhack.ai/). 

QHack is a series of events on quantum computing organized by Xanadu. Events range from scientific talks, code challenges, and an open hackathon. The hackathon runs from February 22nd to February 28th and is open-ended. Example topics:

- Implement an idea from the quantum literature with code. For example, the feature request described in this issue.
- Create a self-contained tutorial or demonstration of an idea from quantum computing. For example, create an interactive Jupyter notebook where you apply the [Variational Quantum Classifier](https://tno-quantum.github.io/ml.classifiers.vc/).
- Submit a Pull Request to an open-source library with a new feature.

For further information on how you can participate in the QHack Open Hackathon, see [this repository](https://github.com/XanaduAI/QHack2023).

Everyone is encouraged to contribute to this issue or alternatively open a separate one.

## Description of feature request

At the moment, we post-process the measurements of a variational circuit in order to facilitate subsequent one-hot encoding representations. This is done in the `QModels`.

[This paper](https://arxiv.org/abs/2212.06663) (by Nico Meyer et al.) presents a way to optimize this post-processing step and also sheds light into our current models. The authors propose a post-processing function $f(\cdot)$ that assigns an integer (corresponding to a class) to a $n$-bit string $b$ as follows:
```math
\begin{align*}
f(b) = \left[b_0 ... b_{m-2}\left(\bigoplus_{i=m-1}^{n-1} b_i\right) \right]_{10}
\end{align*}
```
where $M=2^m$ is the number of classes, $n$ is the number of qubits, and $\left[ \cdot \right]_{10}$ is the decimal representation the argument. For example, if $m=5$ and $n=8$, then
```math
\begin{align*}
f(b_7 b_6 b_5 b_4 b_3 b_2 b_1 b_0) = \left[b_0 b_1 b_2 b_3 \left(b_4 \oplus b_5 \oplus b_6 \oplus b_7 \right) \right]_{10}
\end{align*}
```
and for $b=10110100$ we have
```math
\begin{align*}
f(1 0 1 1 0 1 0 0) = \left[0 0 1 0 \left(1 \oplus 1 \oplus 0 \oplus 1 \right) \right]_{10}
= \left[0 0 1 0 1 \right]_{10} = 5
\end{align*}
```
As usual, the resulting one-hot encoding would be a vector of $M=32$ elements with the 4th element (the index is zero-based!) set to $1$ and all other elements set to zero.

Remaining question: what should we do when $M$ is not a power of $2$?

**Comment by RobertWezemanTNO** [comment]
First version of the `ParityModel` has been implemented. 

The following graph compares the accuracy score for different post-processing strategies for eight features of the [Wine dataset](https://scikit-learn.org/stable/datasets/toy_dataset.html#wine-datasetl). The code to reproduce these results can be found in [this notebook](https://github.com/TNO-Quantum/ml.classifiers.vc/blob/parity-post-processing/quantum_models.ipynb)

![accuracy_score](https://user-images.githubusercontent.com/48919208/221979984-f45e2e5e-9f3c-4f75-834f-8e5a6a6dae19.png)

Still open tasks:
- What should we do when $M$ is not a power of $2$? Currently we simply ignore those class outcomes. These cases needs additional tests.
